---
title: "data_merging_v1"
author: "Denise Upton"
date: "2024-02-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

# set up
library(readr)
library(readxl)
library(lubridate)
library(tidyverse)
library(janitor)
library(DT)
```

## Load COVID and state spending data

```{r}
covariates_covid_statespend <- read_csv("~/Documents/Coding Projects/quant_capstone/data_raw/covariates_covid_statespend_v1.csv") %>%
  arrange(state_fips) %>%
  filter(state_fips<=56) %>%
  rename(date=ym)

```

## Load labor force data

```{r}
covariates_laborforce <- read_csv("~/Google Drive/My Drive/_Wagner/2024-01/Capstone/Data/county_laborforce.csv") %>%
  separate(fips, into = c("delete", "fips"), +9) %>%
  separate(fips, into = c("state_fips", "county_fips"), +2) %>%
  arrange(state_fips) %>%
  filter(state_fips<=56)

```

## Load tidycensus data

```{r}
covariates_census <- read_csv("~/Documents/Coding Projects/quant_capstone/data_raw/covariates_census_v8.csv") %>%
  rename(state_fips=GEOID, county_fips=GEOID2)

```

## Load BLS data

```{r}
BLS_data <- read_csv("~/Documents/Coding Projects/quant_capstone/data_raw/BLS_county_employment_clean.csv") %>%
  mutate(date = format(date, '%Y-%m')) %>%
  separate(FIPS, into = c("state_fips", "county_fips"), -3) %>%
  filter(date >= "2020-07")

```

## Load Seasonally Adjusted BLS data

```{r}
BLS_seas <- read_csv("~/Documents/Coding Projects/quant_capstone/data_raw/BLS_seas_v1.csv") %>%
  mutate(date = format(date, '%Y-%m')) %>%
  rename(Unemployment_Rate_S=Unemployment_Rate) %>%
  separate(FIPS, into = c("state_fips", "county_fips"), -3) %>%
  filter(date >= "2020-07") 

```

## Combine data

```{r}

data <- left_join(BLS_seas, BLS_data, by = c("date", "county_fips", "state_fips"))
data2 <- left_join(data, covariates_laborforce,  by = c("state_fips", "county_fips"))
data3 <- left_join(data2, covariates_census,  by = c("state_fips", "county_fips"))


```

## Test data

```{r}

data3 %>%
  select(-delete, -county, -24)
```

## Export data

```{r}

write.csv(data3, "~/Documents/Coding Projects/quant_capstone/data_clean/data_v3.csv", row.names=FALSE)

```


