---
title: "seasonal_adjustment"
author: "Denise Upton"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

# set up
library(readr)
library(readxl)
library(lubridate)
library(tidyverse)
library(janitor)
library(DT)
library(seasthedata)
library(dplyr)
library(tibble)
```


## Seasonal Adjustment Packages

* https://github.com/christophsax/seasonal
* https://cran.r-project.org/web/packages/seasonal/vignettes/multiple.html
* https://github.com/angusmoore/seasthedata


## Load data - 2015+

```{r}
data1 <- read_csv("~/Documents/Coding Projects/quant_capstone/data_raw/BLS_county_employment_clean.csv") %>%
  separate(FIPS, into = c("state_fips", "county_fips"), -3) %>%
  filter(state_fips <= "56" & state_fips != "11" & countyname != "Bailey County") %>% # Remove PR, Guam, Virgin Islands, DC, Bailey County TX
  select(state_fips, county_fips, date, Unemployment_Rate, countyname) %>%
  arrange(state_fips, county_fips, date) %>%
  group_by(countyname, state_fips, county_fips) 

```


## Merge all data 2015

```{r}
data2 <- read_csv("~/Documents/Coding Projects/quant_capstone/data_raw/BLS_seas_v3.csv")
data1 <- read_csv("~/Documents/Coding Projects/quant_capstone/data_raw/BLS_county_employment_clean.csv") %>%
  separate(FIPS, into = c("state_fips", "county_fips"), -3) %>%
  filter(state_fips <= "56" & state_fips != "11" & countyname != "Bailey County") %>% # Remove PR, Guam, Virgin Islands, DC, Bailey County TX
  select(state_fips, county_fips, date, Unemployment_Rate, countyname) %>%
  arrange(state_fips, county_fips, date) %>%
  group_by(countyname, state_fips, county_fips) 

data_seas_2015 <- left_join(data1, data2, by = c("date", "county_fips", "state_fips"))

write.csv(data_seas_2015, "~/Documents/Coding Projects/quant_capstone/data_raw/BLS_seas_v4.csv", row.names=FALSE)
```


## Adjust data - Outlier detection: Auto

```{r}

data_seas1<- seasthedata(data1)

```


## Adjust data - Outlier detection: 5

```{r}

data_seas2 <- seasthedata(data1,
                          outlier.critical = 5)

```


## Adjust data - Outlier detection: 4

```{r}

data_seas3 <- seasthedata(data1,
                          outlier.critical = 4)
```
## Edit and merge data

```{r}

data_seas1 <- data_seas1 %>%
  rename(unemployment_rate_SA.auto=Unemployment_Rate)

data_seas2 <- data_seas2 %>%
  rename(unemployment_rate_SA.5=Unemployment_Rate)

data_seas3 <- data_seas3 %>%
  rename(unemployment_rate_SA.4=Unemployment_Rate)

data_seas_join <- left_join(data_seas1, data_seas2, by = c("date", "county_fips", "state_fips"))

data_seas_join <- left_join(data_seas_join, data_seas3, by = c("date", "county_fips", "state_fips"))

data_seas_join <- left_join(data_seas_join, data1, by = c("date", "county_fips", "state_fips"))


```

## Export data

```{r}

data_seas_join <- data_seas_join %>%
  select(-1,-6)
  

write.csv(data_seas_join, "~/Documents/Coding Projects/quant_capstone/data_raw/BLS_seas_v3.csv", row.names=FALSE)

```
