---
title: "Capstone Data Cleaning"
output: html_notebook
---

library(readr)
library(dplyr)
library(lubridate)
library(tidyverse)
library(psych)

# Load county-level unemployment data

BLS_county_employment <- read_csv("Documents/Coding Projects/quant_capstone/data_raw/BLS_county_employment.csv")


# Remove observations before 2015

BLS_county_employment <- BLS_county_employment %>% filter(year > "2014")


# Merge in DC data

BLS_county_employment_DC <- read_csv("Documents/Coding Projects/quant_capstone/data_raw/BLS_county_employment_DC.csv")

BLS_county_employment_v2 <- rbind(BLS_county_employment,BLS_county_employment_DC)


# Merge in moratoria dates

moratoria_dates <- read_csv("Documents/Coding Projects/quant_capstone/data_raw/moratoria_dates.csv")

BLS_county_employment_v3 <- merge(BLS_county_employment_v2,moratoria_dates,by=("state"))

view(BLS_county_employment_v3)

# convert control and treatment variable to binary

BLS_county_employment_v3$control <- factor(BLS_county_employment_v3$control,
                            levels = 0:1)
                            
BLS_county_employment_v3$treatment <- factor(BLS_county_employment_v3$treatment,
                            levels = 0:1)
                            
table(BLS_county_employment_v3$control)

BLS_county_employment_v4 <- BLS_county_employment_v3 %>% 
  mutate(date = as.Date(paste(year, month, "01", sep = "-")))

# Add 'first treat' column 

BLS_county_employment_v4$first.treat[BLS_county_employment_v4$treatment == 1] <- BLS_county_employment_v4['federal-end']

BLS_county_employment_v4$first.treat[BLS_county_employment_v4$treatment == 0] <- BLS_county_employment_v4['state-end']


# Export CV

write.csv(BLS_county_employment_v4, "Documents/Coding Projects/quant_capstone/data_clean/BLS_county_employment_clean.csv", row.names=FALSE)