---
title: "seasonal_adjustment"
author: "Denise Upton"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

# set up
library(readr)
library(readxl)
library(lubridate)
library(tidyverse)
library(janitor)
library(DT)
library(seasthedata)
library(dplyr)
library(tibble)
```

## Seasonal Adjustment

* https://github.com/christophsax/seasonal
* https://cran.r-project.org/web/packages/seasonal/vignettes/multiple.html
* https://github.com/angusmoore/seasthedata

## Load data - 2015+

```{r}
data1 <- read_csv("~/Documents/Coding Projects/quant_capstone/data_raw/BLS_county_employment_clean.csv") %>%
  separate(FIPS, into = c("state_fips", "county_fips"), -3) %>%
  filter(state_fips <= "56" & state_fips != "11" & countyname != "Bailey County") %>% # Remove PR, Guam, Virgin Islands, DC, Bailey County TX
  select(state_fips, county_fips, date, Unemployment_Rate, countyname) %>%
  arrange(state_fips, county_fips, date) %>%
  group_by(countyname, state_fips, county_fips) 

```

## Load data - 2019+

```{r}
data2 <- read_csv("~/Documents/Coding Projects/quant_capstone/data_raw/BLS_county_employment_clean.csv") %>%
  select(FIPS, date, Unemployment_Rate) %>%
  group_by(FIPS) %>%
  filter(date >= "2018-01-01")

```

## Adjust data

```{r}

data_seas1<- seasthedata(data1)

```

## Adjust data - Outlier detection: 5

```{r}

data_seas2 <- seasthedata(data1,
                          outlier.critical = 5)

```

## Adjust data - Outlier detection: Low

```{r}

data_seas3 <- seasthedata(data1,
                          outlier.critical = 4)
```
## Explore data

```{r}

summary(data_seas1)

which(is.na(data_seas1$Unemployment_Rate))


```

## Export data

```{r}

write.csv(data_seas1, "~/Documents/Coding Projects/quant_capstone/data_raw/BLS_seas_v2.csv", row.names=FALSE)

```
