---
title: "DiD Initial Exploration"
author: "Camille Preel-Dumas"
date: "2024-01-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# set up
library(readr)
library(lubridate)
library(tidyverse)
library(janitor)


bls_data <- read_csv("/Users/cpreeldumas/Documents/GitHub/quant_capstone/data_clean/BLS_county_employment_clean.csv") %>% 
  clean_names("snake") #convert column names to snake case

#making a numeric version of dates for first treat column
bls_data_did <- bls_data %>% 
  mutate(across(c(state_start, state_end, federal_start, federal_end), mdy)) %>% 
  mutate(across(
    .cols = c(state_start, state_end, federal_start, federal_end), 
    .fns = ~ paste0(year(.x), str_pad(month(.x),
                                      width = 2,
                                      side = "left",
                                      pad = "0")),
    .names = "{.col}_num")) %>% 
  mutate(across(ends_with("_num"), as.numeric)) %>% 
  mutate(first_treat = case_when(
    state == "MA" ~ 0, #never-treated group
    treatment == 1 ~ federal_end_num,
    treatment == 0 ~ state_end_num)) 

bls_data_did %>% 
  group_by(state, treatment, federal_end, state_end, first_treat) %>% 
  tally()

```

